[build]
  command = "npm run build"
  publish = "dist"

# Redirect all /api/ical/* requests to the Netlify function
[[redirects]]
  from = "/api/ical/*"
  to = "/.netlify/functions/fetch-ical/:splat"
  status = 200
